# Checkov Security Scanning Configuration for Missing Table Infrastructure
# This configuration defines security policies and compliance standards

# Framework selection
framework:
  - terraform
  - terraform_plan
  - dockerfile
  - kubernetes
  - github_configuration

# Output configuration
output:
  - cli
  - json
  - sarif
  - github_failed_only

# Check selection
check:
  # Enable all CIS benchmarks
  - CKV_GCP_*
  - CKV_K8S_*
  - CKV_DOCKER_*
  
  # Enable NIST compliance checks
  - CKV2_GCP_*
  
  # Enable custom security checks
  - CKV_TF_*

# Skip specific checks if needed (with justification)
skip-check:
  # Skip certain checks that may not apply to our environment
  # - CKV_GCP_1  # Example: if we have a specific business justification
  
# Severity configuration
severity:
  # Define minimum severity level
  min: MEDIUM
  
# Compliance frameworks
compliance:
  - CIS-GCP-1.3.0
  - NIST-800-53
  - SOC2
  - ISO27001
  - GDPR

# Custom policy directories
external-checks-dir:
  - ./security-policies

# Secrets scanning
secrets:
  enable: true
  
# Dependency scanning
sca:
  enable: true
  
# License scanning
license:
  enable: true

# Soft fail mode for CI/CD (set to false for strict enforcement)
soft-fail: false

# Compact output for better readability
compact: true

# Download external modules for scanning
download-external-modules: true

# Log level
log-level: INFO

# Custom policy enforcement levels
custom-checks:
  # Enforce organization-specific policies
  - name: "missing-table-security-baseline"
    description: "Custom security baseline for Missing Table application"
    severity: HIGH
    
  - name: "gcp-security-hardening"
    description: "GCP-specific security hardening requirements"
    severity: HIGH
    
  - name: "kubernetes-security-standards" 
    description: "Kubernetes security best practices"
    severity: MEDIUM

# Performance settings
performance:
  # Parallel execution
  parallel: true
  
  # Maximum workers
  max-workers: 4
  
  # Timeout settings
  timeout: 300

# Integration settings
integrations:
  github:
    # GitHub integration for PR comments
    enabled: true
    
  slack:
    # Slack notifications for security findings
    enabled: false
    
  jira:
    # JIRA integration for security tickets
    enabled: false