name: Secret Detection

on:
  push:
    branches: [ main, develop, feature/*, hotfix/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # Optional: for Gitleaks Pro features

  detect-secrets:
    name: Detect-Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Run detect-secrets scan
        run: |
          # Run scan and compare with baseline
          detect-secrets scan --baseline .secrets.baseline \
            --exclude-files '.git/.*|node_modules/.*|\.env.*|.*\.lock|package-lock\.json|\.secrets\.baseline'

          # Audit the baseline to check for new secrets
          detect-secrets audit .secrets.baseline --report --fail-on-unaudited

      - name: Upload scan results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-results
          path: .secrets.baseline
          retention-days: 30

  secret-scan-summary:
    name: Secret Scan Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, detect-secrets]
    if: always()

    steps:
      - name: Check scan results
        run: |
          echo "## Secret Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.gitleaks.result }}" == "success" ]; then
            echo "✅ **Gitleaks**: No secrets detected" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Gitleaks**: Secrets detected or scan failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.detect-secrets.result }}" == "success" ]; then
            echo "✅ **Detect-Secrets**: No new secrets detected" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Detect-Secrets**: New secrets detected or scan failed" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Protection Layers" >> $GITHUB_STEP_SUMMARY
          echo "- 🔒 **Pre-commit hook**: detect-secrets (local)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔒 **GitHub Actions**: gitleaks + detect-secrets (CI/CD)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔒 **Gitignored files**: helm values, frontend build.env" >> $GITHUB_STEP_SUMMARY
