"""
Email service using Resend for transactional emails.
"""

from __future__ import annotations

import logging
import os

import resend

logger = logging.getLogger(__name__)

SUPPORT_EMAIL = "support@contact.missingtable.com"


def _support_html_block() -> str:
    """Inline support line for invite-flow HTML emails."""
    return (
        '<p style="color: #6b7280; font-size: 13px; margin-top: 16px;">'
        "Need help? Contact us at "
        f'<a href="mailto:{SUPPORT_EMAIL}" style="color: #2563eb;">{SUPPORT_EMAIL}</a>.'
        "</p>"
    )


def _support_text_block() -> str:
    """Inline support line for invite-flow plain-text emails."""
    return f"Need help? Contact us at {SUPPORT_EMAIL}.\n\n"


class EmailService:
    """Thin wrapper around the Resend SDK for sending transactional emails."""

    def __init__(self) -> None:
        api_key = os.getenv("RESEND_API_KEY")
        if not api_key:
            raise ValueError("RESEND_API_KEY environment variable is required")
        resend.api_key = api_key
        self.from_address = os.getenv("RESEND_FROM_ADDRESS", "noreply@contact.missingtable.com")
        self.app_base_url = os.getenv("APP_BASE_URL", "https://missingtable.com")
        # Optional. If set, every outgoing email includes a Reply-To header
        # pointing at this address so user replies route to a monitored
        # inbox instead of the noreply@ from-address.
        self.reply_to = os.getenv("RESEND_REPLY_TO") or None

    def _build_send_payload(
        self, to_email: str, subject: str, html: str, text: str
    ) -> dict:
        """Common Resend payload with optional Reply-To."""
        payload = {
            "from": self.from_address,
            "to": [to_email],
            "subject": subject,
            "html": html,
            "text": text,
        }
        if self.reply_to:
            # Resend expects a list of strings here.
            payload["reply_to"] = [self.reply_to]
        return payload

    def send_password_reset(self, to_email: str, reset_token: str, username: str) -> bool:
        """
        Send a password reset email via Resend.

        Args:
            to_email: Recipient email address
            reset_token: Signed JWT reset token
            username: User's username (for personalisation)

        Returns:
            True on success, False on failure
        """
        reset_url = f"{self.app_base_url}/?reset_token={reset_token}"

        html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Reset your Missing Table password</title>
</head>
<body style="font-family: Arial, sans-serif; background: #f3f4f6; padding: 32px;">
  <div style="max-width: 480px; margin: 0 auto; background: #fff; border-radius: 8px; padding: 32px;">
    <h2 style="color: #2563eb;">Reset your password</h2>
    <p>Hi <strong>{username}</strong>,</p>
    <p>We received a request to reset the password for your Missing Table account.</p>
    <p>Click the button below to choose a new password. This link expires in <strong>1 hour</strong>.</p>
    <a href="{reset_url}"
       style="display: inline-block; margin: 16px 0; padding: 12px 24px;
              background: #2563eb; color: #fff; border-radius: 6px;
              text-decoration: none; font-weight: bold;">
      Reset Password
    </a>
    <p style="color: #6b7280; font-size: 13px;">
      If you didn't request this, you can safely ignore this email — your password won't change.
    </p>
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
    <p style="color: #9ca3af; font-size: 12px;">Missing Table · missingtable.com</p>
  </div>
</body>
</html>
"""

        text_body = (
            f"Hi {username},\n\n"
            "We received a request to reset the password for your Missing Table account.\n\n"
            f"Reset your password here (link expires in 1 hour):\n{reset_url}\n\n"
            "If you didn't request this, you can safely ignore this email.\n\n"
            "— Missing Table"
        )

        try:
            resend.Emails.send(
                self._build_send_payload(
                    to_email=to_email,
                    subject="Reset your Missing Table password",
                    html=html_body,
                    text=text_body,
                )
            )
            logger.info("password_reset_email_sent", extra={"recipient": to_email[:3] + "***"})
            return True
        except Exception as e:
            logger.error(f"Failed to send password reset email: {e}")
            return False

    def send_invitation(
        self,
        to_email: str,
        invite_code: str,
        invite_type: str | None = None,
        expires_at: str | None = None,
    ) -> bool:
        """
        Send an invitation email with a redemption link.

        Args:
            to_email: Recipient email address
            invite_code: 12-char invite code generated by InviteService
            invite_type: e.g. "club_fan", "team_manager" (used for subject framing)
            expires_at: ISO datetime string for when the code expires
                (rendered as a friendly date in the body if provided)

        Returns:
            True on success, False on failure
        """
        redemption_url = f"{self.app_base_url}/?code={invite_code}"

        # Friendly role label for the subject; falls back to a generic line.
        role_label = {
            "club_manager": "club manager",
            "club_fan": "club follower",
            "team_manager": "team manager",
            "team_player": "team player",
            "team_fan": "team follower",
        }.get(invite_type or "", "")
        subject = (
            f"You're invited to Missing Table as a {role_label}"
            if role_label
            else "You're invited to Missing Table"
        )

        # Optional expiry line.
        expiry_html = ""
        expiry_text = ""
        if expires_at:
            try:
                from datetime import datetime as _dt

                # Accept "2026-05-29T12:34:56+00:00" or trailing Z.
                normalized = expires_at.replace("Z", "+00:00")
                expires_dt = _dt.fromisoformat(normalized)
                expiry_str = expires_dt.strftime("%b %-d, %Y")
                expiry_html = (
                    f'<p style="color: #6b7280; font-size: 13px;">'
                    f"This invitation expires on <strong>{expiry_str}</strong>.</p>"
                )
                expiry_text = f"This invitation expires on {expiry_str}.\n\n"
            except Exception:
                # Bad input format — skip the line rather than fail the send.
                pass

        html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>You're invited to Missing Table</title>
</head>
<body style="font-family: Arial, sans-serif; background: #f3f4f6; padding: 32px;">
  <div style="max-width: 480px; margin: 0 auto; background: #fff; border-radius: 8px; padding: 32px;">
    <h2 style="color: #2563eb;">You're invited! ⚽️</h2>
    <p>Hi there,</p>
    <p>An admin at Missing Table created an invitation for you. Click the
       button below to set up your account.</p>
    <a href="{redemption_url}"
       style="display: inline-block; margin: 16px 0; padding: 12px 24px;
              background: #2563eb; color: #fff; border-radius: 6px;
              text-decoration: none; font-weight: bold;">
      Accept Invitation
    </a>
    <p style="color: #6b7280; font-size: 13px;">
      Or paste this code on the signup page: <strong>{invite_code}</strong>
    </p>
    {expiry_html}
    {_support_html_block()}
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
    <p style="color: #9ca3af; font-size: 12px;">Missing Table · missingtable.com</p>
  </div>
</body>
</html>
"""

        text_body = (
            "Hi there,\n\n"
            "An admin at Missing Table created an invitation for you. Use "
            "the link below to set up your account:\n\n"
            f"{redemption_url}\n\n"
            f"Or paste this code on the signup page: {invite_code}\n\n"
            f"{expiry_text}"
            f"{_support_text_block()}"
            "— Missing Table"
        )

        try:
            resend.Emails.send(
                self._build_send_payload(
                    to_email=to_email,
                    subject=subject,
                    html=html_body,
                    text=text_body,
                )
            )
            logger.info(
                "invitation_email_sent",
                extra={
                    "recipient": to_email[:3] + "***",
                    "invite_type": invite_type,
                },
            )
            return True
        except Exception as e:
            logger.error(f"Failed to send invitation email: {e}")
            return False

    def send_invite_request_approval(self, to_email: str, name: str) -> bool:
        """
        Notify a requester that their join request was approved.

        The actual invitation (with a redemption code) is still created
        manually by an admin via the existing Create Invite UI; this
        email is a heads-up so the requester knows their request was
        seen and accepted.

        Args:
            to_email: Recipient email address
            name: Requester's name (for personalisation)

        Returns:
            True on success, False on failure
        """
        html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Your Missing Table request was approved</title>
</head>
<body style="font-family: Arial, sans-serif; background: #f3f4f6; padding: 32px;">
  <div style="max-width: 480px; margin: 0 auto; background: #fff; border-radius: 8px; padding: 32px;">
    <h2 style="color: #16a34a;">You're approved! 🎉</h2>
    <p>Hi <strong>{name}</strong>,</p>
    <p>Good news — your request to join Missing Table has been approved.</p>
    <p>
      We'll send you a separate invite link shortly so you can finish
      setting up your account. Keep an eye on this inbox.
    </p>
    {_support_html_block()}
    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
    <p style="color: #9ca3af; font-size: 12px;">Missing Table · missingtable.com</p>
  </div>
</body>
</html>
"""

        text_body = (
            f"Hi {name},\n\n"
            "Good news — your request to join Missing Table has been "
            "approved.\n\n"
            "We'll send you a separate invite link shortly so you can "
            "finish setting up your account. Keep an eye on this inbox.\n\n"
            f"{_support_text_block()}"
            "— Missing Table"
        )

        try:
            resend.Emails.send(
                self._build_send_payload(
                    to_email=to_email,
                    subject="Your Missing Table request was approved",
                    html=html_body,
                    text=text_body,
                )
            )
            logger.info(
                "invite_request_approval_email_sent",
                extra={"recipient": to_email[:3] + "***"},
            )
            return True
        except Exception as e:
            logger.error(f"Failed to send invite-request approval email: {e}")
            return False
