services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: missing-table-postgres
    environment:
      POSTGRES_DB: missing_table
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - missing-table-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: missing-table-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - missing-table-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  missing-table-net:
    driver: bridge