#!/usr/bin/env python3
"""
Apply division_id fixes to the database.

This script applies the SQL generated by audit_division_mismatches.py
with proper backup and verification.
"""
import os
import sys
from dotenv import load_dotenv

# Load environment
load_dotenv()
env = os.getenv('APP_ENV', 'local')
load_dotenv(f'.env.{env}', override=True)

from dao.enhanced_data_access_fixed import SupabaseConnection

db_conn = SupabaseConnection()

print(f"=== Applying Division Fixes (Environment: {env}) ===\n")

# Read the SQL file
sql_file = f'fix_division_mismatches_{env}.sql'
if not os.path.exists(sql_file):
    print(f"❌ SQL file not found: {sql_file}")
    print("Run audit_division_mismatches.py first to generate the fix SQL")
    exit(1)

with open(sql_file, 'r') as f:
    sql_content = f.read()

print(f"SQL to apply:\n{'-' * 80}")
print(sql_content)
print('-' * 80)

# Check for --confirm flag
auto_confirm = '--confirm' in sys.argv

if not auto_confirm:
    # Confirm
    response = input("\n⚠️  Apply these changes to the database? (yes/no): ")
    if response.lower() != 'yes':
        print("❌ Aborted. No changes made.")
        exit(0)
else:
    print("\n✅ Auto-confirmed via --confirm flag")

print("\nApplying fixes...")

# Extract the UPDATE statements
import re
update_statements = re.findall(r'UPDATE matches.*?;', sql_content, re.DOTALL)

print(f"\nFound {len(update_statements)} UPDATE statements to execute")

success_count = 0
error_count = 0

for i, statement in enumerate(update_statements, 1):
    # Clean up the statement
    statement = statement.strip()

    # Extract division_id and match IDs for reporting
    div_id_match = re.search(r'SET division_id = (\d+)', statement)
    ids_match = re.search(r'WHERE id IN \((.*?)\)', statement)

    if div_id_match and ids_match:
        new_div_id = div_id_match.group(1)
        match_ids = ids_match.group(1).split(', ')
        print(f"\n{i}. Updating {len(match_ids)} matches to division_id={new_div_id}...")

        try:
            # Execute using Supabase client
            # Parse the match IDs
            match_id_list = [int(mid.strip()) for mid in match_ids]

            # Use Supabase update
            result = db_conn.client.table('matches').update({
                'division_id': int(new_div_id)
            }).in_('id', match_id_list).execute()

            affected = len(result.data)
            print(f"   ✅ Updated {affected} matches")
            success_count += affected

        except Exception as e:
            print(f"   ❌ Error: {e}")
            error_count += 1

print(f"\n{'=' * 80}")
print(f"Summary:")
print(f"  ✅ Successfully updated: {success_count} matches")
if error_count > 0:
    print(f"  ❌ Errors: {error_count}")
print(f"{'=' * 80}")

# Verify the fixes
print("\nVerifying fixes...")
print("\nRe-running audit to check for remaining mismatches...")
os.system(f'APP_ENV={env} uv run python audit_division_mismatches.py')
