#!/usr/bin/env python3
"""
Generate Pydantic models from OpenAPI schema for type-safe API client.

Usage:
    uv run python scripts/generate_api_models.py
"""

import json
import subprocess
import sys
from pathlib import Path


def main() -> None:
    """Generate Pydantic models from OpenAPI schema."""
    backend_dir = Path(__file__).parent.parent
    openapi_file = backend_dir / "openapi.json"
    output_file = backend_dir / "api_client" / "models.py"

    # Ensure openapi.json exists
    if not openapi_file.exists():
        print("❌ openapi.json not found. Generating...")
        subprocess.run(
            [
                "uv",
                "run",
                "python",
                "-c",
                "from app import app; import json; print(json.dumps(app.openapi(), indent=2))",
            ],
            cwd=backend_dir,
            stdout=open(openapi_file, "w"),
            check=True,
        )
        print(f"✅ Generated {openapi_file}")

    # Generate Pydantic models using datamodel-code-generator
    print(f"📝 Generating Pydantic models from {openapi_file}...")

    try:
        subprocess.run(
            [
                "uv",
                "run",
                "datamodel-codegen",
                "--input",
                str(openapi_file),
                "--input-file-type",
                "openapi",
                "--output",
                str(output_file),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--field-constraints",
                "--use-standard-collections",
                "--use-schema-description",
                "--use-title-as-name",
                "--snake-case-field",
                "--strict-nullable",
                "--target-python-version",
                "3.13",
            ],
            check=True,
        )
        print(f"✅ Generated {output_file}")

        # Add header to models file
        with open(output_file, "r") as f:
            content = f.read()

        header = '''"""
Auto-generated Pydantic models from OpenAPI schema.

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: uv run python scripts/generate_api_models.py
"""

'''
        with open(output_file, "w") as f:
            f.write(header + content)

        print("✅ Added header to models file")
        print(f"\n🎉 Success! API models generated at {output_file}")

    except subprocess.CalledProcessError as e:
        print(f"❌ Error generating models: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
