# Terrascan Configuration for Infrastructure Security Scanning

[rules]
# Skip specific rules (with justification in comments)
skip-rules = [
    # Example: Skip if not applicable to your use case
    # "AWS.S3Bucket.DS.High.1043"  # S3 bucket versioning
]

[severity]
# Minimum severity level to report
level = "MEDIUM"

[scan]
# Scan configuration
show-passed = false
verbose = false
config-only = false
find-vuln = true

[output]
type = "sarif"
file = "security/results/terraform-terrascan-results.sarif"

[policy]
# Policy configuration
type = "aws"
path = "security/terraform/custom-policies"

[notifications]
# Webhook for notifications
webhook_url = ""
webhook_token = ""

[logging]
level = "info"

# Custom policy configuration for Missing Table application
[[custom_policies]]
name = "missing-table-security"
description = "Custom security policies for Missing Table application"
rules = [
    {
        name = "require_encryption_at_rest"
        description = "Ensure all storage resources have encryption at rest enabled"
        severity = "HIGH"
        category = "ENCRYPTION"
    },
    {
        name = "require_encryption_in_transit"
        description = "Ensure all communication uses encryption in transit"
        severity = "HIGH"
        category = "ENCRYPTION"
    },
    {
        name = "require_vpc_flow_logs"
        description = "Ensure VPC flow logs are enabled"
        severity = "MEDIUM"
        category = "LOGGING"
    },
    {
        name = "require_mfa_for_admin"
        description = "Ensure MFA is required for administrative access"
        severity = "HIGH"
        category = "IAM"
    }
]