# Quality Gates Configuration
# This file defines the specific thresholds and requirements for each quality gate

# Code Quality Requirements
code_quality:
  backend:
    tools:
      ruff:
        max_violations: 0
        severity_levels: ["error", "warning"]
        exclude_patterns: []
      
      mypy:
        strict_mode: true
        ignore_missing_imports: true
        max_errors: 0
        required_success_codes: [0]
      
      black:
        line_length: 88
        target_versions: ["py313"]
        skip_string_normalization: false
    
    metrics:
      cyclomatic_complexity: 10
      maintainability_index: 80
      lines_of_code_per_function: 50
      
  frontend:
    tools:
      eslint:
        max_errors: 0
        max_warnings: 5
        severity_threshold: "error"
      
      biome:
        max_violations: 0
        check_formatting: true
        check_lint: true
      
      typescript:
        strict_mode: true
        no_emit_on_error: true
        skip_lib_check: false
    
    metrics:
      bundle_size_kb: 2048
      chunk_size_kb: 512
      asset_size_kb: 256

# Security Scanning Requirements
security_scanning:
  vulnerability_thresholds:
    critical: 0
    high: 0
    medium: 5
    low: 10
  
  backend:
    tools:
      bandit:
        severity_threshold: "MEDIUM"
        confidence_threshold: "MEDIUM"
        exclude_tests: true
        skips: []
      
      safety:
        ignore_vulnerabilities: []
        audit_and_monitor: true
        policy_file: ".safety-policy.json"
      
      semgrep:
        ruleset: "auto"
        severity_threshold: "ERROR"
        exclude_patterns: ["tests/*", "**/*_test.py"]
    
    allowed_licenses:
      - "MIT"
      - "Apache-2.0"
      - "BSD-3-Clause"
      - "BSD-2-Clause"
      - "ISC"
      - "Python-2.0"
    
    forbidden_licenses:
      - "GPL-3.0"
      - "AGPL-3.0"
      - "LGPL-3.0"
      - "CPAL-1.0"
  
  frontend:
    tools:
      npm_audit:
        audit_level: "moderate"
        production_only: true
        dev_audit: false
      
      retire_js:
        severity_threshold: "medium"
        include_node: true
      
      lighthouse_security:
        min_score: 90
        categories: ["best-practices", "performance", "accessibility", "seo"]
    
    dependency_scanning:
      auto_merge_patch: true
      auto_merge_minor: false
      security_updates_only: true
  
  container:
    tools:
      trivy:
        severity_levels: ["CRITICAL", "HIGH", "MEDIUM"]
        ignore_unfixed: false
        security_checks: "vuln,config,secret"
      
      grype:
        fail_on: "high"
        scope: "all-layers"
        only_fixed: false
      
      docker_scout:
        cves_only: false
        include_base_image: true
    
    image_requirements:
      no_root_user: true
      read_only_filesystem: true
      non_privileged: true
      distroless_preferred: true

# Testing Requirements
testing:
  coverage:
    backend:
      minimum_line_coverage: 90
      minimum_branch_coverage: 85
      minimum_function_coverage: 95
      exclude_patterns: ["tests/*", "*/migrations/*", "*/__init__.py"]
    
    frontend:
      minimum_line_coverage: 80
      minimum_branch_coverage: 75
      minimum_function_coverage: 85
      exclude_patterns: ["**/*.spec.js", "**/*.test.js", "**/test-utils/*"]
  
  test_requirements:
    backend:
      unit_tests: true
      integration_tests: true
      api_tests: true
      database_tests: true
      security_tests: true
    
    frontend:
      unit_tests: true
      component_tests: true
      e2e_tests: true
      accessibility_tests: true
      visual_regression_tests: false
  
  performance:
    backend:
      response_time_ms: 500
      throughput_rps: 1000
      memory_usage_mb: 512
      cpu_usage_percent: 80
    
    frontend:
      first_contentful_paint_ms: 1500
      largest_contentful_paint_ms: 2500
      cumulative_layout_shift: 0.1
      first_input_delay_ms: 100

# Infrastructure Requirements
infrastructure:
  terraform:
    security_scanning:
      tools: ["checkov", "tfsec", "terrascan"]
      policy_frameworks: ["CIS", "NIST", "SOC2"]
      custom_policies: true
    
    compliance:
      cis_benchmark: true
      nist_compliance: true
      soc2_compliance: true
      gdpr_compliance: true
    
    requirements:
      encryption_at_rest: true
      encryption_in_transit: true
      network_segmentation: true
      least_privilege_iam: true
      monitoring_enabled: true
      backup_strategy: true
  
  kubernetes:
    security_policies:
      pod_security_standards: "restricted"
      network_policies: true
      admission_controllers: true
      rbac_enabled: true
    
    tools:
      kubesec: true
      polaris: true
      falco: true
      opa_gatekeeper: true
    
    compliance:
      cis_k8s_benchmark: true
      nsa_k8s_hardening: true

# Performance Requirements
performance:
  lighthouse:
    thresholds:
      performance: 90
      accessibility: 95
      best_practices: 95
      seo: 90
      pwa: 80
    
    budgets:
      javascript_kb: 1024
      css_kb: 256
      images_kb: 2048
      fonts_kb: 512
      other_kb: 256
    
    core_web_vitals:
      largest_contentful_paint_ms: 2500
      first_input_delay_ms: 100
      cumulative_layout_shift: 0.1
  
  load_testing:
    concurrent_users: 100
    duration_minutes: 10
    ramp_up_seconds: 60
    success_rate_percent: 99.5
    avg_response_time_ms: 500

# Deployment Requirements
deployment:
  strategies:
    production:
      strategy: "blue-green"
      rollback_enabled: true
      health_checks: true
      smoke_tests: true
    
    staging:
      strategy: "rolling"
      parallel_deployments: false
      pre_deployment_tests: true
  
  monitoring:
    health_check_timeout_seconds: 300
    readiness_probe_timeout_seconds: 30
    liveness_probe_timeout_seconds: 30
    post_deployment_monitoring_minutes: 15
  
  rollback:
    automatic_rollback: true
    failure_threshold_percent: 5
    monitoring_window_minutes: 10
    rollback_timeout_minutes: 5

# Notification Requirements
notifications:
  channels:
    slack:
      webhook_required: true
      mention_on_failure: true
      include_artifacts: true
    
    email:
      send_on_failure: true
      send_on_success: false
      include_logs: false
    
    github:
      status_checks: true
      pr_comments: true
      security_alerts: true
  
  escalation:
    critical_failures:
      immediate_notification: true
      escalation_delay_minutes: 15
      on_call_notification: true
    
    repeated_failures:
      threshold_count: 3
      escalation_required: true
      disable_auto_deploy: true

# Compliance and Audit
compliance:
  audit_requirements:
    log_retention_days: 365
    audit_trail: true
    change_tracking: true
    access_logging: true
  
  security_requirements:
    vulnerability_scanning: true
    dependency_tracking: true
    license_compliance: true
    secrets_scanning: true
  
  documentation:
    security_docs: true
    deployment_docs: true
    runbook_required: true
    incident_response_plan: true