"""
Auto-generated Pydantic models from OpenAPI schema.

MANUAL OVERRIDE (2025-10-29): DivisionCreate and DivisionUpdate models
have been manually updated to support league_id. These will be regenerated
from OpenAPI schema after Phase 2 backend API updates.

DO NOT EDIT THIS FILE MANUALLY (except for temporary overrides).
Regenerate with: uv run python scripts/generate_api_models.py
"""

# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-10-06T14:50:01+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AgeGroupCreate(BaseModel):
    name: str = Field(..., title="Name")


class AgeGroupUpdate(BaseModel):
    name: str = Field(..., title="Name")


class DivisionCreate(BaseModel):
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    league_id: int = Field(..., title="League Id")  # MANUAL: Added for league layer support


class DivisionUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    league_id: int | None = Field(None, title="League Id")  # MANUAL: Added for league layer support


class EnhancedGame(BaseModel):
    match_date: str = Field(..., title="Match Date")  # MANUAL: Fixed - backend expects match_date not game_date
    home_team_id: int = Field(..., title="Home Team Id")
    away_team_id: int = Field(..., title="Away Team Id")
    home_score: int = Field(..., title="Home Score")
    away_score: int = Field(..., title="Away Score")
    season_id: int = Field(..., title="Season Id")
    age_group_id: int = Field(..., title="Age Group Id")
    match_type_id: int = Field(
        ..., title="Match Type Id"
    )  # MANUAL: Fixed - backend expects match_type_id not game_type_id
    division_id: int | None = Field(None, title="Division Id")
    status: str | None = Field("scheduled", title="Status")
    created_by: str | None = Field(None, title="Created By")
    updated_by: str | None = Field(None, title="Updated By")
    source: str = Field("manual", title="Source")


class GamePatch(BaseModel):
    """
    Model for partial game updates.
    """

    home_score: int | None = Field(None, title="Home Score")
    away_score: int | None = Field(None, title="Away Score")
    match_status: str | None = Field(None, title="Match Status")
    game_date: str | None = Field(None, title="Game Date")
    home_team_id: int | None = Field(None, title="Home Team Id")
    away_team_id: int | None = Field(None, title="Away Team Id")
    season_id: int | None = Field(None, title="Season Id")
    age_group_id: int | None = Field(None, title="Age Group Id")
    game_type_id: int | None = Field(None, title="Game Type Id")
    division_id: int | None = Field(None, title="Division Id")
    status: str | None = Field(None, title="Status")


class RefreshTokenRequest(BaseModel):
    refresh_token: str = Field(..., title="Refresh Token")


class RoleUpdate(BaseModel):
    user_id: str = Field(..., title="User Id")
    role: str = Field(..., title="Role")
    team_id: int | None = Field(None, title="Team Id")


class SeasonCreate(BaseModel):
    name: str = Field(..., title="Name")
    start_date: str = Field(..., title="Start Date")
    end_date: str = Field(..., title="End Date")


class SeasonUpdate(BaseModel):
    name: str = Field(..., title="Name")
    start_date: str = Field(..., title="Start Date")
    end_date: str = Field(..., title="End Date")


class Team(BaseModel):
    name: str = Field(..., title="Name")
    city: str = Field(..., title="City")
    age_group_ids: list[int] = Field(..., title="Age Group Ids")
    division_id: int = Field(..., title="Division Id")  # MANUAL: Fixed - backend expects singular division_id
    club_id: int | None = Field(None, title="Club Id")
    academy_team: bool | None = Field(False, title="Academy Team")


class TeamGameTypeMapping(BaseModel):
    game_type_id: int = Field(..., title="Game Type Id")
    age_group_id: int = Field(..., title="Age Group Id")


class TeamMappingCreate(BaseModel):
    team_id: int = Field(..., title="Team Id")
    age_group_id: int = Field(..., title="Age Group Id")
    division_id: int = Field(..., title="Division Id")


class TeamUpdate(BaseModel):
    name: str = Field(..., title="Name")
    city: str = Field(..., title="City")
    academy_team: bool | None = Field(False, title="Academy Team")


class UserLogin(BaseModel):
    email: str = Field(..., title="Email")
    password: str = Field(..., title="Password")


class UserProfile(BaseModel):
    display_name: str | None = Field(None, title="Display Name")
    role: str | None = Field(None, title="Role")
    team_id: int | None = Field(None, title="Team Id")
    player_number: int | None = Field(None, title="Player Number")
    positions: list[str] | None = Field(None, title="Positions")


class UserSignup(BaseModel):
    email: str = Field(..., title="Email")
    password: str = Field(..., title="Password")
    display_name: str | None = Field(None, title="Display Name")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


# Re-exports from backend/models/ (single source of truth)
# These allow api_client consumers to import models without knowing the internal layout.

from models.auth import (  # noqa: F401
    AdminPlayerTeamAssignment,
    AdminPlayerUpdate,
    PlayerCustomization,
    PlayerHistoryCreate,
    PlayerHistoryUpdate,
    ProfilePhotoSlot,
    UserProfileUpdate,
)
from models.lineup import LineupSave  # noqa: F401
from models.live_match import GoalEvent, LiveMatchClock, MessageEvent  # noqa: F401
from models.matches import MatchSubmissionData  # noqa: F401
from models.playoffs import AdvanceWinnerRequest, GenerateBracketRequest  # noqa: F401
from models.roster import (  # noqa: F401
    BulkRenumberRequest,
    BulkRosterCreate,
    BulkRosterPlayer,
    JerseyNumberUpdate,
    RenumberEntry,
    RosterPlayerCreate,
    RosterPlayerUpdate,
)


# Invite request models — plain duplicates to avoid EmailStr dependency in client context
class InviteRequestCreate(BaseModel):
    """Create an invite request (public endpoint)."""

    email: str = Field(..., description="Email address of the requester")
    name: str = Field(..., min_length=1, max_length=255, description="Name of the requester")
    team: str | None = Field(None, max_length=255, description="Team or club affiliation")
    reason: str | None = Field(None, description="Reason for wanting to join")


class InviteRequestStatusUpdate(BaseModel):
    """Update invite request status (admin only)."""

    status: str = Field(..., pattern="^(pending|approved|rejected)$")
    admin_notes: str | None = Field(None, description="Admin notes about the decision")
