# Trivy secret scanning configuration
rules:
  - id: aws-access-key-id
    category: AWS
    title: AWS Access Key ID
    severity: HIGH
    keyword:
      - AKIA
    allowlist:
      paths:
        - "**/*.md"
        - "**/README*"
        - "**/docs/**"
      
  - id: jwt-token
    category: JWT
    title: JWT Token
    severity: MEDIUM
    regex: 'eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'
    allowlist:
      paths:
        - "**/test/**"
        - "**/tests/**"
        
  - id: database-password
    category: Database
    title: Database Password
    severity: HIGH
    keyword:
      - password
      - passwd
      - pwd
    allowlist:
      paths:
        - "**/*.example*"
        - "**/template*"