apiVersion: v1
kind: Namespace
metadata:
  name: missing-table
  labels:
    name: missing-table
    security.policy/level: "restricted"
    network.policy/isolation: "enabled"
  annotations:
    description: "Missing Table Sports League Application"
    security.scan/last: ""
---
apiVersion: v1
kind: LimitRange
metadata:
  name: missing-table-limits
  namespace: missing-table
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "100Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "2Gi"
      ephemeral-storage: "5Gi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: missing-table-quota
  namespace: missing-table
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    requests.storage: "10Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"