apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: game-data-consistency
  namespace: testkube
  labels:
    app: missing-table
    test-type: e2e
    layer: backend
spec:
  type: pytest/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/yourusername/missing-table.git
      branch: main
      path: backend/tests
  executionRequest:
    args:
      - "test_enhanced_e2e.py::TestCompleteGameLifecycle::test_game_data_consistency"
      - "-v"
      - "--tb=short"
    variables:
      TEST_MODE:
        name: TEST_MODE
        value: "true"
      SUPABASE_URL:
        name: SUPABASE_URL
        value: "http://host.docker.internal:54321"  # Local Supabase from within container
    workingDir: backend
