apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: backend-health-check
  namespace: testkube
  labels:
    app: missing-table
    test-type: e2e
spec:
  type: curl/test
  content:
    type: string
    data: |
      {
        "command": [
          "curl",
          "-X", "GET",
          "-H", "Content-Type: application/json",
          "http://missing-table-backend.missing-table.svc.cluster.local:8000/api/teams"
        ],
        "expected_status": "200"
      }
