apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "missing-table.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "missing-table.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "missing-table.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        env:
        # Sensitive values from secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: database-url
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: supabase-service-key
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: supabase-jwt-secret
        - name: SERVICE_ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "missing-table.fullname" . }}-secrets
              key: service-account-secret
        # Non-sensitive configuration
        - name: REDIS_URL
          value: "redis://{{ include "missing-table.fullname" . }}-redis:6379"
        # Celery/RabbitMQ configuration (for async API endpoints)
        - name: CELERY_BROKER_URL
          value: "amqp://{{ .Values.celeryWorker.rabbitmq.username }}:{{ .Values.celeryWorker.rabbitmq.password }}@{{ .Values.celeryWorker.rabbitmq.host }}:{{ .Values.celeryWorker.rabbitmq.port }}//"
        - name: CELERY_RESULT_BACKEND
          value: "redis://{{ .Values.celeryWorker.redis.host | default "messaging-redis" }}:{{ .Values.celeryWorker.redis.port | default 6379 }}/0"
        - name: RABBITMQ_URL
          value: "amqp://{{ .Values.celeryWorker.rabbitmq.username }}:{{ .Values.celeryWorker.rabbitmq.password }}@{{ .Values.celeryWorker.rabbitmq.host }}:{{ .Values.celeryWorker.rabbitmq.port }}//"
        - name: ENVIRONMENT
          value: {{ .Values.backend.env.environment | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.backend.env.logLevel | quote }}
        - name: DISABLE_LOGFIRE
          value: {{ .Values.backend.env.disableLogfire | quote }}
        - name: DISABLE_SECURITY
          value: {{ .Values.backend.env.disableSecurity | quote }}
        {{- range $key, $value := .Values.backend.env.extra }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
        {{- if .Values.backend.command }}
        command: {{- toYaml .Values.backend.command | nindent 8 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "missing-table.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  type: ClusterIP
{{- if .Values.backend.service.loadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "missing-table.fullname" . }}-backend-lb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend-lb
spec:
  ports:
  - port: {{ .Values.backend.service.loadBalancer.port }}
    targetPort: 8000
    name: http
  selector:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  type: LoadBalancer
{{- end }}