apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "missing-table.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "missing-table.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "missing-table.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: {{ .Values.frontend.env.nodeEnv | quote }}
        - name: VUE_APP_API_URL
          value: {{ .Values.frontend.env.apiUrl | quote }}
        - name: VUE_APP_SUPABASE_URL
          value: {{ .Values.frontend.env.supabaseUrl | quote }}
        - name: VUE_APP_SUPABASE_ANON_KEY
          value: {{ .Values.frontend.env.supabaseAnonKey | quote }}
        - name: VUE_APP_DISABLE_SECURITY
          value: {{ .Values.frontend.env.vueAppDisableSecurity | quote }}
        {{- range $key, $value := .Values.frontend.env.extra }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
        {{- if .Values.frontend.command }}
        command: {{- toYaml .Values.frontend.command | nindent 8 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "missing-table.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  type: {{ .Values.frontend.service.type }}
  {{- if eq .Values.frontend.service.type "LoadBalancer" }}
  {{- if .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  {{- end }}