{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "messaging-platform.fullname" . }}-prometheus
  labels:
    app: prometheus
    {{- include "messaging-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: prometheus
{{- end }}
