{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "messaging-platform.fullname" . }}-prometheus-config
  labels:
    app: prometheus
    {{- include "messaging-platform.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval | default "15s" }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval | default "15s" }}
      external_labels:
        cluster: {{ .Values.prometheus.externalLabels.cluster | default "k3s-local" | quote }}
        environment: {{ .Values.prometheus.externalLabels.environment | default "development" | quote }}

    {{- if .Values.grafanaCloud.enabled }}
    # Grafana Cloud remote write configuration
    remote_write:
      - url: {{ .Values.grafanaCloud.remoteWriteUrl | quote }}
        basic_auth:
          username: {{ .Values.grafanaCloud.username | quote }}
          password: {{ .Values.grafanaCloud.password | quote }}
        queue_config:
          capacity: {{ .Values.prometheus.remoteWrite.queueConfig.capacity | default 10000 }}
          max_shards: {{ .Values.prometheus.remoteWrite.queueConfig.maxShards | default 10 }}
          min_shards: {{ .Values.prometheus.remoteWrite.queueConfig.minShards | default 1 }}
          max_samples_per_send: {{ .Values.prometheus.remoteWrite.queueConfig.maxSamplesPerSend | default 500 }}
          batch_send_deadline: {{ .Values.prometheus.remoteWrite.queueConfig.batchSendDeadline | default "5s" }}
    {{- end }}

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape RabbitMQ metrics
      - job_name: 'rabbitmq'
        scrape_interval: {{ .Values.prometheus.rabbitmqScrapeInterval | default "30s" }}
        static_configs:
          - targets: ['{{ include "messaging-platform.fullname" . }}-rabbitmq:15692']
        metrics_path: '/metrics'
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'rabbitmq'

      # Scrape Celery exporter
      - job_name: 'celery'
        scrape_interval: {{ .Values.prometheus.celeryScrapeInterval | default "30s" }}
        static_configs:
          - targets: ['{{ include "messaging-platform.fullname" . }}-celery-exporter:9808']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'celery-exporter'
{{- end }}
