---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "messaging-platform.fullname" . }}-redis
  labels:
    {{- include "messaging-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    {{- include "messaging-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
