apiVersion: v2
name: missing-table
description: A Helm chart for Missing Table - MLS Next sports league standings and schedules
type: application
version: 0.1.0
appVersion: "1.4.0"
home: https://github.com/silverbeer/missing-table
maintainers:
  - name: silverbeer
keywords:
  - sports
  - mls
  - league
  - standings
  - fastapi
  - vue
dependencies: []
annotations:
  category: Sports
  licenses: Apache-2.0