# Dev environment configuration for GKE
# Overrides values.yaml for GKE dev deployment

# Namespace for dev
namespace: missing-table-dev

# Backend configuration
backend:
  replicaCount: 1

  image:
    repository: us-central1-docker.pkg.dev/missing-table/missing-table/backend
    tag: latest
    pullPolicy: Always  # Always pull latest for dev

  env:
    # Supabase Cloud Dev Environment
    databaseUrl: "postgresql://postgres.ppgxasqgqbnauvxozmjw:bdn8ZKX-jmn2rwh!xey@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
    environment: "development"
    logLevel: "info"
    disableLogfire: "true"
    disableSecurity: "true"
    extra:
      SUPABASE_URL: "https://ppgxasqgqbnauvxozmjw.supabase.co"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ3hhc3FncWJuYXV2eG96bWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODQ5MTAsImV4cCI6MjA2NzA2MDkxMH0.5R1E-CpsZJU_4tRaaYrq4P00IhIrsIjqo0zQuX-rBHQ"
      SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ3hhc3FncWJuYXV2eG96bWp3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTQ4NDkxMCwiZXhwIjoyMDY3MDYwOTEwfQ.QMPR89Da_ozg29Y50QVzTgrmmu2bq2rz5D5PiM-rZk0"
      SUPABASE_JWT_SECRET: "K2y0g5mRi2ovGOwaPnawQjEoMrbBoHF5gSkAtmGYBc43ETdDVQl3h7hGuaA5DZZQ1ymXtMhggA6OlX7TySH43w=="
      SERVICE_ACCOUNT_SECRET: "TRuSNNHcVAb86bIBy465es-8k-c4DVeQ_oSKKFP9Tr4"
      CORS_ORIGINS: "http://34.133.125.204:8080"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  service:
    loadBalancer:
      enabled: true  # Enable LoadBalancer for external access
      port: 8000

# Frontend configuration
frontend:
  replicaCount: 1

  image:
    repository: us-central1-docker.pkg.dev/missing-table/missing-table/frontend
    tag: prod  # Use production build for faster startup
    pullPolicy: Always  # Always pull latest for dev

  env:
    nodeEnv: "production"  # Use production mode for pre-built app
    # Backend external LoadBalancer IP
    apiUrl: "http://34.135.217.253:8000"
    supabaseUrl: "https://ppgxasqgqbnauvxozmjw.supabase.co"
    supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ3hhc3FncWJuYXV2eG96bWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODQ5MTAsImV4cCI6MjA2NzA2MDkxMH0.5R1E-CpsZJU_4tRaaYrq4P00IhIrsIjqo0zQuX-rBHQ"
    vueAppDisableSecurity: "true"
    extra: {}

  # Use Dockerfile CMD (serve -s dist -l 8080) instead of npm run serve
  command: []

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    initialDelaySeconds: 10  # Production image starts quickly
    periodSeconds: 10

  readinessProbe:
    initialDelaySeconds: 5  # Production image starts quickly
    periodSeconds: 5

  service:
    type: LoadBalancer  # Expose frontend via LoadBalancer

# Redis configuration
redis:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 250m  # Bumped for Autopilot minimum
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    size: 1Gi
    storageClass: "standard-rwo"  # GKE default storage class
