
"""
Auto-generated tests for /api/matches endpoint
Generated by: MT Testing Crew - Forge Agent
Date: 2025-11-10 09:53:41
"""

from backend.app import app
from fastapi.testclient import TestClient

client = TestClient(app)


def test_get_all_matches():
    """Test retrieving all matches successfully"""
    response = client.get("/api/matches")
    assert response.status_code == 200
    assert isinstance(response.json(), list)


def test_add_new_match():
    """Test adding a new match successfully"""
    response = client.post("/api/matches", json={
        "home_team_id": 1,
        "away_team_id": 2,
        "match_date": "2023-10-15T14:00:00Z",
        "location": "Stadium A"
    })
    assert response.status_code == 201
    assert response.json().get("message") == "Match created successfully"


def test_missing_required_fields():
    """Test adding a match with missing required fields"""
    response = client.post("/api/matches", json={
        "home_team_id": 1
    })
    assert response.status_code == 400
    assert "missing fields" in response.json().get("error")


def test_invalid_data_types():
    """Test adding a match with invalid data types"""
    response = client.post("/api/matches", json={
        "home_team_id": "one",
        "away_team_id": "two",
        "match_date": "invalid-date",
        "location": 123
    })
    assert response.status_code == 400
    assert "invalid data types" in response.json().get("error")


def test_boundary_date_values():
    """Test adding a match with boundary date values"""
    response = client.post("/api/matches", json={
        "home_team_id": 1,
        "away_team_id": 2,
        "match_date": "1970-01-01T00:00:00Z",
        "location": "Stadium A"
    })
    assert response.status_code == 201
    assert response.json().get("message") == "Match created with boundary date"


def test_special_characters_in_location():
    """Test adding a match with special characters in location"""
    response = client.post("/api/matches", json={
        "home_team_id": 1,
        "away_team_id": 2,
        "match_date": "2023-10-15T14:00:00Z",
        "location": "<script>alert('XSS')</script>"
    })
    assert response.status_code == 400
    assert "invalid characters" in response.json().get("error")


def test_sql_injection_in_location():
    """Test SQL injection attempt in location field"""
    response = client.post("/api/matches", json={
        "home_team_id": 1,
        "away_team_id": 2,
        "match_date": "2023-10-15T14:00:00Z",
        "location": "Stadium A'; DROP TABLE matches; --"
    })
    assert response.status_code == 400
    assert "invalid input" in response.json().get("error")


def test_unauthorized_access():
    """Test unauthorized access attempt"""
    response = client.post("/api/matches", headers={"Authorization": "Bearer invalid_token"}, json={
        "home_team_id": 1,
        "away_team_id": 2,
        "match_date": "2023-10-15T14:00:00Z",
        "location": "Stadium A"
    })
    assert response.status_code == 401
    assert "Unauthorized" in response.json().get("error")


def test_large_number_of_matches():
    """Test performance with a large number of matches"""
    response = client.get("/api/matches", params={"limit": 1000})
    assert response.status_code == 200
    assert len(response.json()) <= 1000


def test_concurrent_requests():
    """Test server handling of concurrent requests"""
    # This is a placeholder for actual concurrent request testing
    response = client.get("/api/matches")
    assert response.status_code == 200
