#!/usr/bin/env python3
"""
Comprehensive database backup script for MLS Next development.
Creates JSON backups of all tables with timestamp.

A backup is complete or it is not written (SB-1068). The old script caught
every error per table, dropped that table, wrote the file anyway and exited 0.
With local Supabase down on 2026-09-14 it produced a 206-byte, zero-table
backup, printed "Backup completed successfully!", and that file became the
newest one — which is what `restore --latest` picks, and restore clears every
table before it loads.

Production is backed up unless `--env local` says otherwise, and APP_ENV is
ignored (SB-1069): shells here export APP_ENV=local, which is how a bare backup
twice backed up a stopped local database instead of production.

Exit codes: 0 a complete backup was written, 1 the backup failed and nothing
was written, 2 bad arguments, 130 cancelled.
"""

import gzip
import json
import os
import re
import sys
import time
import traceback
import zlib
from dataclasses import dataclass
from datetime import datetime, timedelta
from functools import partial
from pathlib import Path
from urllib.parse import urlparse

import httpx
from dotenv import load_dotenv
from postgrest.exceptions import APIError
from supabase import Client, create_client

try:
    from supabase_auth.errors import AuthRetryableError
except ImportError:  # older supabase releases ship the auth client as gotrue
    from gotrue.errors import AuthRetryableError

# Add backend to path for shared modules
backend_path = Path(__file__).parent.parent / "backend"
sys.path.append(str(backend_path))

# Production unless told otherwise (SB-1069), and never read from APP_ENV:
# shells here export APP_ENV=local, which is how a bare
# `./scripts/db_tools.sh backup` twice backed up a stopped local database
# instead of production. configure() fills these in from --env.
DEFAULT_ENV = "prod"
ENVIRONMENTS = ("prod", "local")
LOCAL_HOSTS = {"127.0.0.1", "localhost", "0.0.0.0", "::1", "host.docker.internal"}

app_env = DEFAULT_ENV
env_path: Path | None = None
url: str | None = None
key: str | None = None
db_url: str | None = None
supabase: Client | None = None

DEFAULT_BACKUP_DIR = Path.home() / "backups" / "missing-table"

PAGE_SIZE = 1000
AUTH_PAGE_SIZE = 1000

# Transient failures (network, timeouts, 5xx) are retried after these delays.
RETRY_DELAYS = (1, 2, 4)  # seconds
MAX_ATTEMPTS = len(RETRY_DELAYS) + 1

# Replaced in tests so retries do not really wait.
sleep = time.sleep

# Tables intentionally excluded from backups
EXCLUDED_TABLES = {
    "user_profiles",  # Managed per-environment (different auth.users UUIDs)
    "schema_version",  # Internal tracking, recreated by migrations
    "service_accounts",  # Contains API keys - managed per-environment
    "ingest_failures",  # Operational diagnostics (SB-829) - regenerated by the next
    # scrape, and per-environment: prod's unresolved names say
    # nothing about local's data
    # FreeRADIUS tables were dropped in migration 20260404201640_drop_radius_tables.sql
}

# Tables to back up, in order of dependencies.
# NOTE: user_profiles is EXCLUDED from backups
# Reason: Users and profiles are managed per-environment, not synced between dev/prod
# - Each environment has its own auth.users with different UUIDs
# - user_profiles.id must match auth.users.id (no FK constraint but logical requirement)
# - Restoring user_profiles from another environment causes UUID mismatches
# - See docs/FOREIGN_KEY_DECISION.md for details
# - Use backend/manage_users.py to create users in each environment
TABLES_TO_BACKUP = [
    # Reference data (no dependencies)
    "age_groups",
    "leagues",  # Added for league layer support - must come before divisions
    "divisions",  # Now depends on leagues
    "match_types",
    "seasons",
    # Clubs (before teams - teams have club_id foreign key)
    "clubs",
    # Per-club notification channels (Telegram/Discord) for live match updates
    "club_notification_channels",
    # Teams and mappings
    "teams",
    "team_mappings",
    "team_match_types",
    "team_aliases",
    # Team management
    "team_manager_assignments",
    # Players
    "players",
    "player_team_history",
    # Matches
    "matches",
    # Playoff brackets (depends on matches)
    "playoff_bracket_slots",
    # Match-related data
    "match_of_the_week",
    "match_events",
    "match_lineups",
    "player_match_stats",
    # Tournaments (depends on seasons, age_groups, leagues)
    "tournaments",
    "tournament_age_groups",
    # Audit and activity logs
    "audit_events",
    "audit_teams",
    "login_events",
    # Invitations
    "invitations",
    "invite_requests",
    # Channel access requests (Telegram/Discord)
    "channel_access_requests",
    # Intentionally excluded (see EXCLUDED_TABLES):
    # - user_profiles: managed per-environment (different auth.users UUIDs)
    # - service_accounts: contains API keys, managed per-environment
    # - schema_version: internal tracking, recreated by migrations
    # - rad* tables: FreeRADIUS protocol tables, not application data
]

# auth.users is read through the Admin API and stored under this key.
AUTH_USERS_KEY = "auth_users"

# supabase/seed.sql populates these in every environment. Empty here means the
# backup did not come from a working database, whatever else it contains.
# User-generated tables (players, match_events, ...) are legitimately empty for
# most teams and are deliberately not on this list.
REQUIRED_NON_EMPTY = ("age_groups", "leagues", "divisions", "match_types", "seasons")

BACKUP_NAME = re.compile(r"^database_backup_(\d{8}_\d{6})\.json\.gz$")


class BackupError(Exception):
    """A backup that cannot be trusted. Nothing is written when this is raised."""


def environment_mismatch(env: str, supabase_url: str | None) -> str | None:
    """Why this URL cannot belong to this environment, or None if it can.

    A .env.prod pointing at localhost, or a .env.local pointing at the cloud,
    would otherwise back up one database under the other's name.
    """
    is_local = (urlparse(supabase_url or "").hostname or "") in LOCAL_HOSTS
    if env == "prod" and is_local:
        return f"--env prod, but SUPABASE_URL is {supabase_url}, a local address"
    if env == "local" and not is_local:
        return f"--env local, but SUPABASE_URL is {supabase_url}, which is not a local address"
    return None


def configure(env: str) -> None:
    """Load one environment's credentials from backend/.env.<env>.

    There is no fallback to backend/.env: quietly loading some other file is
    how a backup ends up labelled as one environment and holding another.
    """
    global app_env, env_path, url, key, db_url, supabase
    app_env = env
    env_path = backend_path / f".env.{env}"
    if not env_path.exists():
        raise BackupError(
            f"{env_path} not found — it holds the credentials for backing up {env}"
        )
    load_dotenv(env_path, override=True)
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY")
    db_url = os.getenv("DATABASE_URL")
    supabase = create_client(url, key) if url and key else None


def is_transient(error: BaseException) -> bool:
    """Worth retrying: the network, a timeout or a server error — not a bad request."""
    if isinstance(error, (httpx.TransportError, AuthRetryableError)):
        return True
    if isinstance(error, APIError):
        # Supabase's gateway answers a slow query with a 504 (SB-1057).
        return str(error.code).startswith("5")
    return False


def describe_error(error: BaseException) -> str:
    """One line saying what went wrong, readable without a traceback."""
    if isinstance(error, BackupError):
        return str(error)
    if isinstance(error, httpx.ConnectError):
        return f"cannot connect ({error})"
    if isinstance(error, httpx.TimeoutException):
        return f"timed out ({type(error).__name__})"
    if isinstance(error, APIError):
        return f"PostgREST {error.code}: {error.message or 'no message'}"
    message = str(error).strip() or "no message"
    return f"{type(error).__name__}: {message}"


def with_retries(action, describe: str):
    """Run `action`, retrying transient failures with backoff. Raises the last error."""
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            return action()
        except Exception as error:
            if attempt == MAX_ATTEMPTS or not is_transient(error):
                raise
            delay = RETRY_DELAYS[attempt - 1]
            print(
                f"  ⚠ {describe}: {describe_error(error)} — retry {attempt}/{MAX_ATTEMPTS - 1} in {delay}s"
            )
            sleep(delay)


def fetch_page(
    table_name: str,
    select_columns: str,
    offset: int,
    size: int = PAGE_SIZE,
    with_count: bool = False,
):
    """One page of a table. With `with_count`, the response also carries the table's row count."""
    query = supabase.table(table_name)
    query = (
        query.select(select_columns, count="exact")
        if with_count
        else query.select(select_columns)
    )
    return query.range(offset, offset + size - 1).execute()


def check_for_new_tables(tables_to_backup: list) -> list:
    """
    Check if there are tables in the database not included in the backup list.
    Returns list of tables that are missing from backups.
    """
    try:
        import psycopg2

        if not db_url:
            print("  ⚠ Cannot check for new tables: DATABASE_URL not set")
            return []

        conn = psycopg2.connect(db_url)
        cur = conn.cursor()
        cur.execute("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
            AND table_type = 'BASE TABLE'
        """)
        db_tables = {row[0] for row in cur.fetchall()}
        conn.close()

        backup_set = set(tables_to_backup) | EXCLUDED_TABLES
        missing = db_tables - backup_set

        if missing:
            print("=" * 60)
            print("⚠️  WARNING: Tables exist in database but NOT in backup list:")
            for table in sorted(missing):
                print(f"    - {table}")
            print()
            print("  Add these to 'TABLES_TO_BACKUP' in backup_database.py")
            print("  Or add to 'EXCLUDED_TABLES' if intentionally skipped.")
            print("=" * 60)
            print()

        return list(missing)

    except ImportError:
        print("  ⚠ psycopg2 not available, skipping table check")
        return []
    except Exception as e:
        print(f"  ⚠ Could not check for new tables: {e}")
        return []


def check_connection() -> None:
    """Prove the database answers before reading thirty tables from it.

    With the database down, the old script tried every table, printed a ✗ for
    each, and still wrote a file. This fails once, up front, naming the
    environment — because the usual cause is backing up the wrong one.
    """
    try:
        with_retries(
            partial(fetch_page, "seasons", "id", 0, size=1), "connection check"
        )
    except Exception as error:
        message = (
            f"Cannot read from Supabase at {url} ({app_env}): {describe_error(error)}"
        )
        if app_env == "local" and isinstance(error, httpx.TransportError):
            message += (
                "\n  Local Supabase is not answering. Start it with `npx supabase start`,"
                "\n  or back up production, the default: `./scripts/db_tools.sh backup`."
            )
        raise BackupError(message) from error


def backup_table(table_name: str, select_columns: str = "*") -> list:
    """Every row of one table, a page at a time.

    Raises rather than returning what it managed to read: a table that is
    silently short is worse than a backup that visibly failed.
    """
    print(f"Backing up {table_name}...")
    rows: list = []
    expected = None
    offset = 0

    while True:
        page = with_retries(
            partial(
                fetch_page, table_name, select_columns, offset, with_count=offset == 0
            ),
            f"{table_name} (rows from {offset})",
        )
        if offset == 0:
            expected = page.count
        batch = page.data or []
        rows.extend(batch)
        if len(batch) < PAGE_SIZE:
            break
        offset += PAGE_SIZE

    # A short page is read as the end of the table. If PostgREST's max-rows cap
    # is below PAGE_SIZE, that happens on page one and the rest is never read.
    if expected is not None and len(rows) < expected:
        raise BackupError(
            f"read {len(rows)} of {expected} rows — PostgREST returned short pages, "
            f"or rows were deleted during the backup"
        )

    print(f"  ✓ {len(rows)} records")
    return rows


def backup_auth_users() -> list:
    """auth.users via the Admin API (not reachable through REST), identity fields only."""
    print("Backing up auth.users...")
    all_users = []
    page = 1
    while True:
        response = with_retries(
            partial(supabase.auth.admin.list_users, page=page, per_page=AUTH_PAGE_SIZE),
            f"auth.users (page {page})",
        )
        # SDK returns a list of User objects
        users = (
            response if isinstance(response, list) else getattr(response, "users", [])
        )
        if not users:
            break
        for u in users:
            # Serialize to dict, keeping only non-sensitive identity fields
            all_users.append(
                {
                    "id": str(u.id),
                    "email": u.email,
                    "role": getattr(u, "role", None),
                    "email_confirmed_at": str(u.email_confirmed_at)
                    if u.email_confirmed_at
                    else None,
                    "created_at": str(u.created_at) if u.created_at else None,
                    "last_sign_in_at": str(u.last_sign_in_at)
                    if u.last_sign_in_at
                    else None,
                    "user_metadata": getattr(u, "user_metadata", {}),
                    "app_metadata": getattr(u, "app_metadata", {}),
                }
            )
        if len(users) < AUTH_PAGE_SIZE:
            break
        page += 1
    print(f"  ✓ {len(all_users)} auth users")
    return all_users


def collect_tables(tables: list[str]) -> tuple[dict, dict[str, str]]:
    """Back up each table, carrying on past a failure so the report names every one.

    Returns the rows collected and, for each table that failed, why.
    """
    steps = [(table, partial(backup_table, table)) for table in tables]
    steps.append((AUTH_USERS_KEY, backup_auth_users))

    collected: dict = {}
    failures: dict[str, str] = {}
    for index, (name, step) in enumerate(steps):
        try:
            collected[name] = step()
        except Exception as error:
            failures[name] = describe_error(error)
            print(f"  ✗ {name}: {failures[name]}")
            if is_transient(error):
                # Its retries are spent, so the database has stopped answering.
                # Every remaining table would sit through the same backoff only
                # to fail the same way.
                for remaining, _ in steps[index + 1 :]:
                    failures[remaining] = (
                        "not attempted — the database stopped responding"
                    )
                break
    return collected, failures


def row_counts(backup_data: dict) -> dict[str, int]:
    """Rows per table in a backup payload."""
    tables = backup_data.get("tables") or {}
    return {name: len(rows) for name, rows in tables.items() if isinstance(rows, list)}


def validate_backup(
    backup_data: dict,
    expected_tables: list[str],
    required_non_empty: tuple[str, ...] = REQUIRED_NON_EMPTY,
) -> list[str]:
    """Everything wrong with a backup payload; empty when it is safe to restore from."""
    tables = backup_data.get("tables")
    if not isinstance(tables, dict):
        return ["backup has no 'tables' section"]

    problems = []
    for name in [*expected_tables, AUTH_USERS_KEY]:
        if name not in tables:
            problems.append(f"{name}: missing")
        elif not isinstance(tables[name], list):
            problems.append(
                f"{name}: expected a list of rows, got {type(tables[name]).__name__}"
            )

    for name in required_non_empty:
        if isinstance(tables.get(name), list) and not tables[name]:
            problems.append(
                f"{name}: empty, but supabase/seed.sql populates it in every environment"
            )

    return problems


def backup_timestamp(path: Path) -> datetime | None:
    """When a backup was taken, read from its file name; None if it is not a backup file."""
    match = BACKUP_NAME.match(path.name)
    return datetime.strptime(match.group(1), "%Y%m%d_%H%M%S") if match else None


def usability_problems(backup_data: dict) -> list[str]:
    """Why a backup cannot be restored from at all; empty when it can.

    Narrower than validate_backup() on purpose. That one demands every table on
    today's list, which is right for a backup being written now. A backup taken
    before a table was added lacks it and is still a good backup of its day —
    judging old files by today's list would have retention delete the whole
    history the day a table is added.
    """
    tables = backup_data.get("tables")
    if not isinstance(tables, dict) or not tables:
        return ["no tables"]
    return [
        f"{name}: missing or empty"
        for name in REQUIRED_NON_EMPTY
        if not isinstance(tables.get(name), list) or not tables[name]
    ]


@dataclass(frozen=True)
class BackupFile:
    """A backup on disk and whether it can be restored from.

    `problems` is empty for a usable backup and lists what is wrong with an
    unusable one. It is None when the file could not be read at all (permissions,
    I/O): its state is unknown, so retention decides nothing about it.
    """

    path: Path
    taken_at: datetime
    problems: tuple[str, ...] | None

    @property
    def usable(self) -> bool:
        return self.problems == ()


def inspect_backup(path: Path) -> BackupFile | None:
    """Read a backup file and judge it; None for files that are not backups."""
    taken_at = backup_timestamp(path)
    if taken_at is None:
        return None
    try:
        with gzip.open(path, "rt", encoding="utf-8") as f:
            data = json.load(f)
    except (EOFError, ValueError, gzip.BadGzipFile, zlib.error) as error:
        # Truncated, not gzip, not JSON: definitely unusable.
        return BackupFile(path, taken_at, (f"corrupt: {describe_error(error)}",))
    except OSError:
        return BackupFile(path, taken_at, None)
    if not isinstance(data, dict):
        return BackupFile(path, taken_at, ("not a backup object",))
    return BackupFile(path, taken_at, tuple(usability_problems(data)))


def plan_retention(
    backups: list[BackupFile],
    now: datetime,
    keep_days: int = 30,
    keep_monthly: bool = True,
) -> list[BackupFile]:
    """Which backups the retention policy deletes, oldest first.

      1. Unusable backups go, whatever their age: they can only mislead a restore.
      2. Usable backups from the last `keep_days` days stay.
      3. Older usable backups: the newest of each calendar month stays
         (with `keep_monthly`); the rest go.
      4. The newest usable backup always stays, however old — if nightly backups
         stop for months, the last good copy must not age out.
      5. A file that could not be read is never deleted.

    The old policy kept "the newest file of the month", which would have kept an
    empty backup and deleted the good ones before it.
    """
    cutoff = now - timedelta(days=keep_days)
    usable = sorted(
        (b for b in backups if b.usable), key=lambda b: b.taken_at, reverse=True
    )

    keep = {usable[0].path} if usable else set()
    archived_months: set[str] = set()
    for backup in usable:
        if backup.taken_at >= cutoff:
            keep.add(backup.path)
            continue
        month = backup.taken_at.strftime("%Y-%m")
        if keep_monthly and month not in archived_months:
            archived_months.add(month)
            keep.add(backup.path)

    doomed = [b for b in backups if b.problems is not None and b.path not in keep]
    return sorted(doomed, key=lambda b: b.taken_at)


def newest_usable_backup(backup_dir: Path) -> BackupFile | None:
    """The most recent backup that can be restored from, skipping unusable ones."""
    if not backup_dir.exists():
        return None
    for path in sorted(backup_dir.glob("database_backup_[0-9]*.json.gz"), reverse=True):
        backup = inspect_backup(path)
        if backup is not None and backup.usable:
            return backup
    return None


def freshness_problem(
    newest: BackupFile | None, now: datetime, max_age_hours: float
) -> str | None:
    """Why the backups are stale, or None when the newest usable one is recent enough."""
    if newest is None:
        return "no usable backup found"
    age_hours = (now - newest.taken_at).total_seconds() / 3600
    if age_hours > max_age_hours:
        return f"newest usable backup is {newest.path.name}, {age_hours:.0f}h old (limit {max_age_hours:g}h)"
    return None


def failure_report(failures: dict[str, str]) -> str:
    lines = [f"{len(failures)} table(s) could not be backed up:"]
    lines += [f"  - {name}: {reason}" for name, reason in failures.items()]
    return "\n".join(lines)


def write_backup(backup_data: dict, backup_file: Path) -> None:
    """Write to a temporary file, read it back, and only then give it its real name.

    The real name is what `restore --latest` looks for, so a file cut short by a
    full disk, a crash or Ctrl-C must never carry it.
    """
    partial_file = backup_file.with_name(f".{backup_file.name}.partial")
    try:
        with gzip.open(partial_file, "wt", encoding="utf-8") as f:
            json.dump(backup_data, f, indent=2, default=str)
        with gzip.open(partial_file, "rt", encoding="utf-8") as f:
            written = json.load(f)
        if row_counts(written) != row_counts(backup_data):
            raise BackupError(
                f"{partial_file.name} did not read back with the rows that were written"
            )
        os.replace(partial_file, backup_file)
    except (OSError, EOFError, ValueError) as error:
        raise BackupError(
            f"Could not write {backup_file}: {describe_error(error)}"
        ) from error
    finally:
        partial_file.unlink(missing_ok=True)


def create_backup(backup_dir: Path | None = None) -> Path:
    """Create a complete database backup, or raise BackupError having written nothing."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = backup_dir or DEFAULT_BACKUP_DIR
    try:
        backup_dir.mkdir(parents=True, exist_ok=True)
    except OSError as error:
        raise BackupError(
            f"Cannot create backup directory {backup_dir}: {describe_error(error)}"
        ) from error

    backup_file = backup_dir / f"database_backup_{timestamp}.json.gz"

    print(f"Creating database backup: {backup_file}")
    print("=" * 50)

    check_connection()

    # Safety check: warn if database has tables not in backup list
    check_for_new_tables(TABLES_TO_BACKUP)

    tables, failures = collect_tables(TABLES_TO_BACKUP)
    if failures:
        raise BackupError(failure_report(failures))

    backup_data = {
        "backup_info": {
            "timestamp": timestamp,
            "created_at": datetime.now().isoformat(),
            "version": "1.1",
            "app_env": app_env,
            "supabase_url": url,
        },
        "tables": tables,
    }
    backup_data["backup_info"]["row_counts"] = row_counts(backup_data)

    problems = validate_backup(backup_data, TABLES_TO_BACKUP)
    if problems:
        raise BackupError(
            "Backup is incomplete:\n" + "\n".join(f"  - {p}" for p in problems)
        )

    write_backup(backup_data, backup_file)

    counts = backup_data["backup_info"]["row_counts"]
    print("=" * 50)
    print("✅ Backup completed successfully!")
    print(f"📁 File: {backup_file}")
    print(f"🌐 Environment: {app_env} ({url})")
    print(f"📊 Size: {backup_file.stat().st_size / 1024:.1f} KB")
    print(f"📈 Total records: {sum(counts.values())}")
    print(f"📋 Tables backed up: {len(counts)}")

    return backup_file


def list_backups(backup_dir: Path | None = None):
    """List all available backups."""
    backup_dir = backup_dir or DEFAULT_BACKUP_DIR

    if not backup_dir.exists():
        print(f"No backups directory found at {backup_dir}.")
        return []

    # Only match timestamp-formatted backups (YYYYMMDD_HHMMSS)
    backup_files = list(backup_dir.glob("database_backup_[0-9]*.json.gz"))
    backup_files.sort(reverse=True)  # Most recent first

    if not backup_files:
        print("No backup files found.")
        return []

    print("Available backups:")
    print("-" * 40)

    for i, backup_file in enumerate(backup_files):
        try:
            with gzip.open(backup_file, "rt", encoding="utf-8") as f:
                data = json.load(f)
                info = data.get("backup_info", {})
                created = info.get("created_at", "Unknown")
                unusable = usability_problems(data)
                missing = [
                    p
                    for p in validate_backup(data, TABLES_TO_BACKUP)
                    if p.endswith(": missing")
                ]
                if unusable:
                    flag = "  ⚠ UNUSABLE — do not restore"
                elif missing:
                    flag = (
                        f"  (older format: lacks {len(missing)} table(s) added since)"
                    )
                else:
                    flag = ""

                print(f"{i+1}. {backup_file.name}{flag}")
                print(f"   📅 Created: {created}")
                print(f"   🌐 Environment: {info.get('app_env', 'unknown')}")
                print(f"   📊 Records: {sum(row_counts(data).values())}")
                print(f"   💾 Size: {backup_file.stat().st_size / 1024:.1f} KB")
                print()

        except Exception as e:
            print(f"{i+1}. {backup_file.name} (corrupted - {describe_error(e)})")

    return backup_files


def cleanup_old_backups(
    backup_dir: Path | None = None,
    keep_days: int = 30,
    keep_monthly: bool = True,
    dry_run: bool = False,
    now: datetime | None = None,
) -> list[Path]:
    """Apply the retention policy (see plan_retention).

    Returns the files deleted — or, with `dry_run`, the files that would be.
    """
    backup_dir = backup_dir or DEFAULT_BACKUP_DIR
    if not backup_dir.exists():
        return []

    backups = [
        backup
        for path in sorted(backup_dir.glob("database_backup_[0-9]*.json.gz"))
        if (backup := inspect_backup(path)) is not None
    ]
    if not backups:
        print("No backups to clean up.")
        return []

    for backup in backups:
        if backup.problems is None:
            print(f"  ⚠ Could not read {backup.path.name}; leaving it alone")

    doomed = plan_retention(backups, now or datetime.now(), keep_days, keep_monthly)
    policy = f"{keep_days}-day daily + {'monthly archive' if keep_monthly else 'no monthly archive'}"
    if not doomed:
        print(f"Retention: keeping all {len(backups)} backup(s) ({policy}).")
        return []

    print(f"{'Would delete' if dry_run else 'Deleting'} {len(doomed)} backup(s):")
    removed: list[Path] = []
    for backup in doomed:
        if backup.problems:
            reason = "unusable — " + "; ".join(backup.problems)
        else:
            reason = "outside retention"
        if dry_run:
            print(f"  - {backup.path.name} ({reason})")
            removed.append(backup.path)
            continue
        try:
            backup.path.unlink()
        except OSError as error:
            print(f"  ✗ Could not delete {backup.path.name}: {describe_error(error)}")
            continue
        print(f"  ✓ Deleted {backup.path.name} ({reason})")
        removed.append(backup.path)

    print(f"Retention: {len(backups) - len(removed)} backup(s) kept ({policy}).")
    return removed


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns the process exit code.

    `db_tools.sh migrate prod` pushes migrations only when this exits 0, and
    `run_backup.sh` logs a failed nightly backup from it — so a backup that is
    missing anything has to exit non-zero.
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Database backup utility",
        epilog=(
            "Exit codes: 0 success (backup written, or backups fresh), 1 failure (nothing "
            "written, or backups stale), 2 bad arguments, 130 cancelled."
        ),
    )
    parser.add_argument(
        "--env",
        choices=ENVIRONMENTS,
        default=DEFAULT_ENV,
        help=f"Environment to back up (default: {DEFAULT_ENV}). APP_ENV is ignored.",
    )
    parser.add_argument("--list", action="store_true", help="List available backups")
    parser.add_argument("--cleanup", action="store_true", help="Run retention cleanup")
    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=DEFAULT_BACKUP_DIR,
        help=f"Directory to store backups (default: {DEFAULT_BACKUP_DIR})",
    )
    parser.add_argument(
        "--keep-days",
        type=int,
        default=30,
        help="Number of days to keep daily backups (default: 30)",
    )
    parser.add_argument(
        "--no-monthly",
        action="store_true",
        help="Disable monthly archive retention",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="With --cleanup: show what retention would delete, and delete nothing",
    )
    parser.add_argument(
        "--check-fresh",
        type=float,
        metavar="HOURS",
        help="Exit 1 unless the newest usable backup is at most HOURS old (needs no credentials)",
    )

    args = parser.parse_args(argv)
    backup_dir: Path = args.backup_dir

    try:
        if args.list:
            list_backups(backup_dir)
            return 0

        if args.cleanup:
            cleanup_old_backups(
                backup_dir=backup_dir,
                keep_days=args.keep_days,
                keep_monthly=not args.no_monthly,
                dry_run=args.dry_run,
            )
            return 0

        if args.check_fresh is not None:
            newest = newest_usable_backup(backup_dir)
            problem = freshness_problem(newest, datetime.now(), args.check_fresh)
            if problem or newest is None:
                print(f"❌ Backups are stale: {problem} (in {backup_dir})")
                return 1
            print(f"✓ Backups are fresh: {newest.path.name} (in {backup_dir})")
            return 0

        configure(args.env)

        if supabase is None:
            print(
                f"❌ Backup of {app_env} failed: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set "
                f"in {env_path}. No backup was written."
            )
            return 1

        mismatch = environment_mismatch(app_env, url)
        if mismatch:
            print(
                f"❌ Backup of {app_env} failed: {mismatch} (from {env_path}). No backup was written."
            )
            return 1

        print(f"✓ Environment: {app_env} ({url})")
        backup_file = create_backup(backup_dir=backup_dir)

    except KeyboardInterrupt:
        print("\n❌ Backup cancelled by user. No backup was written.")
        return 130
    except BackupError as error:
        print(f"\n❌ Backup of {app_env} failed. No backup was written.\n{error}")
        return 1
    except Exception as error:
        traceback.print_exc()
        print(
            f"\n❌ Backup of {app_env} failed unexpectedly. No backup was written: {describe_error(error)}"
        )
        return 1

    print("\n💡 To restore this backup, run:")
    print(f"   python scripts/restore_database.py {backup_file.name}")
    print()

    # The backup is already safely written; failing to prune old ones must not
    # turn that into a reported failure.
    try:
        cleanup_old_backups(
            backup_dir=backup_dir,
            keep_days=args.keep_days,
            keep_monthly=not args.no_monthly,
        )
    except Exception as error:
        print(
            f"⚠ Backup written, but retention cleanup failed: {describe_error(error)}"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
