services:
  postgres:
    image: supabase/postgres:15.1.0.147
    container_name: supabase-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  rest:
    image: postgrest/postgrest:v11.2.2
    container_name: supabase-rest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres-data: