# ArgoCD Namespace with Security Labels and Annotations
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: production
    security.missing-table.io/level: "high"
    compliance.missing-table.io/framework: "soc2"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    security.missing-table.io/description: "ArgoCD GitOps namespace with enhanced security controls"
    compliance.missing-table.io/auditing: "enabled"
    networking.missing-table.io/ingress-policy: "restricted"
---
# Network Policy for ArgoCD namespace isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-network-policy
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # Allow ingress from ingress controller
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    # Allow ingress from monitoring namespace
    - namespaceSelector:
        matchLabels:
          name: monitoring
    # Allow internal ArgoCD communication
    - namespaceSelector:
        matchLabels:
          name: argocd
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 2746
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to Git repositories and container registries
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 22
  # Allow access to Kubernetes API server
  - to: []
    ports:
    - protocol: TCP
      port: 6443
  # Allow internal namespace communication
  - to:
    - namespaceSelector:
        matchLabels:
          name: argocd
---
# Security Context Constraints for ArgoCD
apiVersion: v1
kind: LimitRange
metadata:
  name: argocd-limits
  namespace: argocd
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
# Resource Quota for ArgoCD namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocd-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
    pods: "20"
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "50"
    configmaps: "50"